### ISSUE TITLE
Wasmer 0.3.1 instance memory leak

### ISSUE THREAD

**Issue by Polygens** [wasmerio/wasmer-go#181] opened 2021-02-04 14:48 UTC
### Describe the bug

When instantiating `wasmer.Instance` using `wasmModule.InstantiateWithImportObject(wasmImportObject)` memory remains allocated. Closing the instance does not free the memory causing a slow build up of memory causing our containers to go OOM.

### Steps to reproduce

I've created a demo repository at https://github.com/Polygens/wasmer-leak to reproduce the problem.
More info in the readme.

You can change the iteration count to surpass the memory limit: 
https://github.com/Polygens/wasmer-leak/blob/e106a28cf6fbcaa8709c9402d60b3fee51957e0e/main.go#L36

### Expected behavior

After every iteration of the for loop in the demo repo I would expect memory usage to remain consistent after calling instance.Close()
Or at least garbage collected before going OOM.

### Actual behavior

Instead of memory being released after every iteration it builds up.
Example of using 320 iterations just before getting OOM killed:
![image](https://user-images.githubusercontent.com/3582318/106908643-c43da500-66ff-11eb-92ed-174d48ec0a60.png)

### Additional context

We are using WASI so we were unable to verify if this is fixed in Wasmer-go 1.0. We tried closing the memory and the instance but that does not seem to alleviate the problem.

**Comment by Hywan** [comment] 2021-02-04 14:52
Thanks for the detailed issue! I really appreciate it!

The problem was known and has been resolved already. We are about to release `wasmer-go` 1.0.0 in a couple of days. Stay tuned :-)!

I'm closing the issue, but feel free to re-open if you believe the problem is still present. Thanks!

**Closed by Hywan** 2021-02-04 14:52 UTC
Labels: 🐞 bug
