### ISSUE TITLE
Can we pass arrays to wasmer?

### ISSUE THREAD

**Issue by AchalaSB** [wasmerio/wasmer-go#125] opened 2020-03-12 07:47 UTC
Hi @Hywan , 

Suppose I have coded a rust program taking arrays as formal argument.
Suppose I have converted this rust program into WASM binary.
Using go-ext-wasm, can get the result of that function?
Is this achievable ?

Thanks

**Comment by Hywan** [comment] 2020-03-12 12:56
For the moment, Wasm only supports `i32`, `i64`, `f32` and `f64`. WIT (WebAssembly Interface Types) is a draft for a new standard to allow more complex types. We are working hard on it, https://github.com/wasmerio/wasmer/blob/master/lib/interface-types/. Allow, it's a duplicate of #75.

Although, it is possible. You can convert your array as a slice, use the pointer and the length to write or read it, but you need to convert the binary data into your real values.

**Comment by AchalaSB** [comment] 2020-03-12 13:02
Thanks for the update.
When can we expect this feature? Any roadmap.

BTW what about bytes?

**Comment by AchalaSB** [comment] 2020-03-12 14:47
Hey, @Hywan  
I tried with this example. 
```
use std::slice;
pub extern fn pop_front(slice: &mut &mut [i32]) {
    let ptr = slice.as_mut_ptr();
    let len = slice.len();
    *slice = unsafe { slice::from_raw_parts_mut(ptr.offset(1), len - 1) };
}
pub extern fn test() {
    let mut slice = &mut [0, 1, 2, 3][..];
    pop_front(&mut slice);
}
fn main() {
}
```
Go code is here https://play.golang.org/p/xjYWjumHpyx

But it ended up with error 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a38c3]

goroutine 1 [running]:
main.main()
        /home/achala/codes/wasm-play/hello.go:18 +0x183
exit status 2
```
What's wrong in this?

**Comment by AchalaSB** [comment] 2020-03-13 10:57
@Hywan 
Is this function suitable for wasmer? If so, how do I call this function in wasmer?
```
#[no_mangle]
pub extern fn sum_array(ptr: *const i32, len: i32) -> i32 {
    let array = unsafe {
        std::slice::from_raw_parts(ptr, len as usize)
    };
    array.iter().sum::<i32>()
}
```
I'm getting result as 0.

**Comment by Hywan** [comment] 2020-03-13 11:08
You might be interesting by this article, https://mnt.io/2018/08/22/from-rust-to-beyond-the-webassembly-galaxy/. It explains how to use pointer, arrays, bytes etc.

**Comment by Hywan** [comment] 2020-03-13 11:09
> When can we expect this feature? Any roadmap.

WIT is really a draft, we have implemented `wasmer-interface-types` to be up-to-date with the draft, but the feature won't be enabled in the next weeks. There is no official roadmap.

**Comment by AchalaSB** [comment] 2020-03-13 14:10
Okay thanks for article.
Is there any method for calling the arrays/slices in go-wasmer, to give value during runtime? 

BTW Why `memoryLength := instance.Memory.Length()` always giving me constant value `1114112`
size is not calculating based on wasm memory size?

**Comment by Hywan** [comment] 2021-02-04 15:59
It's the size of the memory. Not of its content. The number of memory pages depend on your Wasm module. It can grow over time :-).

**Closed by Hywan** 2021-02-04 15:59 UTC
Labels: ❓ question
