### ISSUE TITLE
Problem while doing go get

### ISSUE THREAD

**Issue by kleash** [wasmerio/wasmer-go#46] opened 2019-06-20 15:27 UTC
### Summary

I tried doing ```go get github.com/wasmerio/go-ext-wasm/wasmer```

but it throws me error:
```
../go/src/github.com/wasmerio/go-ext-wasm/wasmer/bridge.go:162:87: cannot use (*_Ctype_struct___13)(instanceContext) (type *_Ctype_struct___13) as type *_Ctype_struct___16 in argument to _Cfunc_wasmer_instance_context_data_get
```
### Additional details

My ```go env```

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build913563706=/tmp/go-build -gno-record-gcc-switches"
```

Initially, I was getting error:
```
ubuntu@ip:~/1$ go get github.com/wasmerio/go-ext-wasm/wasmer
# github.com/wasmerio/go-ext-wasm/wasmer
exec: "gcc": executable file not found in $PATH
```

Than I did ```sudo apt install gcc``` and installed gcc.

Post that the go get for wasmer is giving mentioned error.

Any pointer on what might have gone wrong?

**Comment by Hywan** [comment] 2019-06-21 08:09
Thanks for raising the issue. Unfortunately, I'm not able to reproduce. The CI server uses Ubuntu for the Linux tests, maybe you can find interesting info: https://circleci.com/gh/wasmerio/go-ext-wasm/80?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

**Comment by Hywan** [comment] 2019-06-21 08:09
Basic question: What Go version do you have?

**Comment by kleash** [comment] 2019-06-21 09:52
> Basic question: What Go version do you have?

```go version go1.11 linux/amd64```

**Comment by kleash** [comment] 2019-06-21 10:22
> Thanks for raising the issue. Unfortunately, I'm not able to reproduce. The CI server uses Ubuntu for the Linux tests, maybe you can find interesting info: https://circleci.com/gh/wasmerio/go-ext-wasm/80?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

I see the servers have go1.12. Is it a requirement to have go1.12.x + for wasmer?

**Comment by Hywan** [comment] 2019-06-21 12:26
I don't know. I never tried with Go 1.11. Can you try with 1.12 to see if it fixes the problem?

**Comment by kleash** [comment] 2019-06-21 17:15
Thanks, it's working with 1.12

**Comment by FlorianFranzen** [comment] 2020-03-30 15:35
I just hit the same issue under Go 1.14 on NixOS, but it does not appear under 1.13.8.

**Comment by AdamSLevy** [comment] 2020-03-30 16:05
I hit this or a similar problem in my own fork. Go 1.14 has better type checking for CGo. It caught a type errors in the bridge.go file that I had modified. I believe that is what is going on here.

**Comment by FlorianFranzen** [comment] 2020-04-05 13:17
@Hywan So I assume that means go-ext-wasm is not yet go 14 compatible?

**Comment by Hywan** [comment] 2020-04-06 07:54
The CI tests against Go 1.13. I'll try with Go 1.14.

**Comment by Hywan** [comment] 2020-04-06 07:56
Check https://github.com/wasmerio/go-ext-wasm/pull/129

**Comment by Hywan** [comment] 2020-04-06 08:07
I just tested on macOS with Go 1.14 and had no problem. @AdamSLevy Do you know what should change in `bridge.go`?

**Comment by FlorianFranzen** [comment] 2020-05-04 13:32
@Hywan Can also no longer reproduce this with v0.3.2 and Go 1.14.1. Thank you for looking into this.

**Comment by Hywan** [comment] 2020-05-05 14:10
@FlorianFranzen Good to hear!

**Comment by AdamSLevy** [comment] 2020-05-20 02:27
This got closed but I think the issue is still present. The issue is here:

https://github.com/wasmerio/go-ext-wasm/blob/0e9bfcdfc7025cdafd17345047277387ef960d25/wasmer/bridge.go#L519-L524

That should be an instanceContext not an instance in that function.

**Comment by Hywan** [comment] 2020-06-09 11:15
Sorry for the late reply. @AdamSLevy Are you willing to open a PR to address the issue please?

**Comment by AdamSLevy** [comment] 2020-06-12 02:30
Thanks for the opportunity but I'm too busy. Please don't wait for me to fix this.

**Comment by Hywan** [comment] 2020-06-12 14:21
:+1:

**Comment by jubianchi** [comment] 2020-12-16 14:28
I'm closing this issue as there where no new feedback on this problem.

**Closed by jubianchi** 2020-12-16 14:28 UTC
Labels: ❓ question
